name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set env
        run: yarn config set enableImmutableInstalls false
      - name: Install modules
        run: yarn

      - name: Lint
        run: yarn run lint
